### PR TITLE
[backstage] Introduce new plugin for upcoming Backstage integration.

### PR DESCRIPTION
**Pull request by axdotl**
We're about to connect kobs and [Backstage](https://backstage.io/). This plugin should facilitate this.

- [x] I added a [CHANGELOG](https://github.com/kobsio/kobs/blob/master/CHANGELOG.md) entry for this change.
- [ ] I adjusted the corresponding [documentation](https://github.com/kobsio/kobs/tree/main/docs) for this change.
- [ ] I adjusted the [values.yaml](https://github.com/kobsio/kobs/blob/main/deploy/helm/kobs/values.yaml) file and the [documentation for all values](https://github.com/kobsio/kobs/blob/main/docs/installation/helm.md).

### CODE REVIEW

**Comment by axdotl** [comment]
@ricoberger Can you point me to why the Go Test step is failing?

**Comment by ricoberger** [comment]
@axdotl what is the status of this PR?

**Comment by axdotl** [comment]
The plugin itself is still desired and I like to keep this PR open.
As soon as I've capacity I will take care of this. 
Either I'll solve the conflicts in this PR or I'll start with a fresh branch to get it working (because of the kobs architecture rework).

I hope that's okay for you.

**Comment by axdotl** [comment]
Close for now - too many things changed in the meantime. Will come back to this at later point in time.

**Pull request closed without merging**
